version: "3.9"

services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./api/postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - 5050:80
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - pgadmin
    env_file: .env
    command: pm2-runtime start /usr/app/index.js
